const WH=WeddingHub;let data=WH.getData();
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
function openView(name){$$('.admin-view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('.side-link[data-view]').forEach(l=>l.classList.toggle('active',l.dataset.view===name));$('#sidebar').classList.remove('open');scrollTo(0,0)}
$$('.side-link[data-view]').forEach(l=>l.onclick=()=>openView(l.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>openView(b.dataset.jump));$('#menuButton').onclick=()=>$('#sidebar').classList.toggle('open');
function overview(){$('#metricGuests').textContent=data.guests.length;$('#metricAttending').textContent=data.guests.filter(g=>g.rsvp==='attending').length;$('#metricPending').textContent=data.guests.filter(g=>g.rsvp==='pending').length;const preview=data.guests.find(g=>g.rsvp==='attending')||data.guests[0];if(preview)$$('a[href*="demo-james"]').forEach(a=>a.href=`event.html?token=${preview.token}`)}
WH.countdown(data.wedding.date,c=>$('#adminCountdown').innerHTML=c.passed?'<strong>Today we celebrate love</strong>':[['Days',c.days],['Hours',c.hours],['Minutes',c.minutes],['Seconds',c.seconds]].map(([l,v])=>`<div><strong>${String(v).padStart(2,'0')}</strong><span>${l}</span></div>`).join(''));
const form=$('#weddingForm');Object.entries(data.wedding).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=k==='date'?String(v).slice(0,16):v});form.onsubmit=async e=>{e.preventDefault();new FormData(form).forEach((v,k)=>data.wedding[k]=v);WH.saveData(data);try{await WeddingHubAPI.saveWedding(data);WH.toast(WeddingHubAPI.isOnline()?'Wedding details published to the API':'Wedding details saved locally')}catch(error){WH.toast(`Saved locally · API: ${error.message}`)}};
const categories=[...new Set(WH.templates().map(t=>t.category))];$('#templateCategory').innerHTML+=categories.map(c=>`<option>${c}</option>`).join('');
function templates(){const q=$('#templateSearch').value.toLowerCase(),cat=$('#templateCategory').value;$('#templateGrid').innerHTML=WH.templates().filter(t=>(!cat||t.category===cat)&&(`${t.name} ${t.category}`.toLowerCase().includes(q))).map(t=>`<article class="template-card tone-${t.tone} ${data.wedding.templateId===t.id?'selected':''}"><div class="template-preview"><span>${t.premium?'PREMIUM':'WEDDING'}</span><small>Together with their families</small><h3>${WH.escape(data.wedding.brideName)} <i>&</i><br>${WH.escape(data.wedding.groomName)}</h3><p>${WH.formatDate(data.wedding.date)}</p></div><div class="template-meta"><span><strong>${t.name}</strong><small>${t.category}</small></span><button data-template="${t.id}">${data.wedding.templateId===t.id?'Selected':'Try design'}</button></div></article>`).join('');$$('[data-template]').forEach(b=>b.onclick=()=>{data.wedding.templateId=b.dataset.template;WH.saveData(data);templates();WH.toast('Design applied — your details were preserved')})}$('#templateSearch').oninput=templates;$('#templateCategory').onchange=templates;
function events(){$('#eventAdminList').innerHTML=data.events.map(e=>`<article class="manage-card"><span class="calendar-tile"><b>${e.date.slice(-2)}</b>${new Date(e.date+'T12:00').toLocaleString('en',{month:'short'}).toUpperCase()}</span><div class="manage-copy"><h3>${WH.escape(e.name)} <i class="status ${e.status}">${e.status}</i></h3><p>${e.time} · ${WH.escape(e.venue)}</p><small>${WH.escape(e.description)}</small></div><button class="icon-button">•••</button></article>`).join('')}
function guests(filter=''){const list=data.guests.filter(g=>g.name.toLowerCase().includes(filter.toLowerCase()));$('#guestTable').innerHTML='<div class="table-row table-head"><span>Guest</span><span>Category</span><span>Invitation</span><span>RSVP</span><span>Party</span><span></span></div>'+list.map(g=>`<div class="table-row"><span class="guest-cell"><i>${g.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</i><span><strong>${WH.escape(g.name)}</strong><small>${WH.escape(g.email)}</small></span></span><span>${g.category}</span><span><b class="status ${g.invitationStatus}">${g.invitationStatus}</b></span><span>${g.rsvp}</span><span>${g.partySize}</span><button data-copy="${g.token}">↗ Copy</button></div>`).join('');$$('[data-copy]').forEach(b=>b.onclick=()=>copyInvite(b.dataset.copy))}$('#guestSearch').oninput=e=>guests(e.target.value);
function copyInvite(token){const url=new URL(`event.html?token=${token}`,location.href).href;navigator.clipboard?.writeText(url);WH.toast('Personalized invitation link copied')}$('#shareButton').onclick=()=>copyInvite(data.guests[0].token);
function content(){$('#photoAdminGrid').innerHTML=WH.published(data.photos).map(p=>`<figure><img src="${p.url}" alt="${WH.escape(p.caption)}"><figcaption>${WH.escape(p.caption)}</figcaption></figure>`).join('');$('#storyAdminList').innerHTML=data.stories.sort((a,b)=>a.order-b.order).map(s=>`<article><span>☷</span><div><small>${s.year}</small><strong>${WH.escape(s.title)}</strong><p>${WH.escape(s.content)}</p></div><b class="status ${s.status}">${s.status}</b></article>`).join('')}
function announcements(){$('#announcementList').innerHTML=data.announcements.map(a=>`<article class="manage-card"><span class="manage-icon">◉</span><div class="manage-copy"><h3>${WH.escape(a.title)} <i class="status ${a.status}">${a.status}</i></h3><p>${WH.escape(a.message)}</p><small>${WH.formatDate(a.date)}</small></div></article>`).join('')}
function messages(){$('#messageList').innerHTML=data.messages.map(m=>`<article class="manage-card"><span class="activity-avatar">${m.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div class="manage-copy"><h3>${WH.escape(m.name)} <i class="status ${m.status}">${m.status}</i></h3><p>“${WH.escape(m.message)}”</p><small>${WH.formatDate(m.date)}</small></div><button class="button secondary">Moderate</button></article>`).join('')}
const modal=$('#modal'),modalContent=$('#modalContent');function showModal(html){modalContent.innerHTML=html;modal.classList.add('open')}$('#modalClose').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};
$('#addGuest').onclick=()=>{showModal('<p class="eyebrow">Personalized invitation</p><h2>Add a guest</h2><form id="guestForm" class="modal-form"><label>Full name<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>Phone<input name="phone"></label><label>Category<select name="category"><option>Family</option><option>Friends</option><option>Colleagues</option></select></label><button class="button primary">Create invitation</button></form>');$('#guestForm').onsubmit=async e=>{e.preventDefault();const g=Object.fromEntries(new FormData(e.target));Object.assign(g,{id:'guest_'+Date.now(),token:'invite-'+crypto.randomUUID(),invitationStatus:'pending',rsvp:'pending',partySize:1});try{const created=await WeddingHubAPI.addGuest(g);if(created){g.token=created.token;g.apiInvitationId=created.invitation.id}}catch(error){WH.toast(`Guest saved locally · API: ${error.message}`)}data.guests.unshift(g);WH.saveData(data);guests();overview();modal.classList.remove('open');WH.toast(WeddingHubAPI.isOnline()?'Guest and API invitation created':'Guest and demo invitation created')} };
$('#newAnnouncement').onclick=()=>{showModal('<p class="eyebrow">Instant guest update</p><h2>New announcement</h2><form id="announcementForm" class="modal-form"><label>Title<input name="title" required></label><label>Message<textarea name="message" rows="5" required></textarea></label><label>Status<select name="status"><option value="published">Publish now</option><option value="draft">Save as draft</option></select></label><button class="button primary">Save announcement</button></form>');$('#announcementForm').onsubmit=async e=>{e.preventDefault();const a=Object.fromEntries(new FormData(e.target));Object.assign(a,{id:'ann_'+Date.now(),date:new Date().toISOString().slice(0,10)});data.announcements.unshift(a);WH.saveData(data);try{await WeddingHubAPI.saveWedding(data)}catch(error){console.warn(error)}announcements();modal.classList.remove('open');WH.toast(a.status==='published'?'Announcement published for guests':'Saved as draft')} };
overview();templates();events();guests();content();announcements();messages();
if(location.hash)openView(location.hash.slice(1));
WeddingHubAPI.bootstrap(data).then(result=>{data=result.data;const status=$('#apiStatus');status.textContent=result.online?'● API connected':'● Local demo';status.classList.toggle('online',result.online);overview();templates();events();guests();content();announcements();messages()});